### PR TITLE
README: Add link to Hubs sessions episode 2

### PR DESCRIPTION
**Pull request by JohnSundell**
Episode 2 is now available on YouTube

### CODE REVIEW

**Comment by JohnSundell** [comment]
@spotify/objc-dev

**Comment by rastersize** [comment]
How about extending this with some thumbnails? Visual stuff is always nice and make the hit-target massive. Could look something like (thumbnails could obviously be different):

- [**Episode 1: Content Loading Chain**<br>Hub Framework Sessions - Episode 1](https://youtu.be/XbMFPtxk_4Q)
- [**Episode 2: Creating Components**<br>Hub Framework Sessions - Episode 1](https://youtu.be/JpeQhKAen8M)

### Markdown:
```md
- [**Episode 1: Content Loading Chain**<br><img src="http://c.rastersize.com/1z253M1i2b2i/Hub_Framework-Sessions-Alt-E01@2x.png" width=320 alt="Hub Framework Sessions - Episode 1">](https://youtu.be/XbMFPtxk_4Q)
- [**Episode 2: Creating Components**<br><img src="http://c.rastersize.com/3F1c1c3M1D2s/Hub_Framework-Sessions-Alt-E02@2x.png" width=320 alt="Hub Framework Sessions - Episode 1">](https://youtu.be/JpeQhKAen8M)
```

**Comment by JohnSundell** [comment]
That's an awesome suggestion @rastersize - will do that! Thanks! 😄

**Comment by JohnSundell** [comment]
Wait a second @rastersize, those images are hosted on your own server or something? Not sure if we can use that here 😅

**Comment by JohnSundell** [comment]
Merging this for now, and we can update to the thumbnails later once we've figured out where to host them.

**Comment by rastersize** [comment]
@JohnSundell Yeah I pushed the images to my CloudApp account. Just to show how it would look asap :)

We can fix a better hosting method. Also the images I used are in an insane resolution (leading to about 1-2 MB for each) so need to resize them first as well :)

**Pull request merged**
