### PR TITLE
Add proposed value for the scroll handler to be used by features

### PR DESCRIPTION
**Pull request by nataliq**
This PR moves the logic from the `HUBViewControllerDefaultScrollHandler` to the `HUBViewController` so that it could be reused by features that want to provide custom scroll handler to override some behaviour but don't want to replicate this logic.

### CODE REVIEW

**Comment by JohnSundell** [comment]
@Goos I think it'd be great if you reviewed this, since you've been working a lot on the scrolling behaviors 😄

**Comment by Goos** [comment]
@JohnSundell, @nataliq I'm kind of hesitant to move back scrolling behaviour to the view controller as it's way too large already. How about exposing the HUBDefaultScrollHandler as part of the interface for subclassing instead?

**Comment by nataliq** [comment]
@Goos I like that idea. Also currently if you want to provide different value for 1-2 things you still have to implement all methods..

**Comment by JohnSundell** [comment]
@Goos @nataliq Awesome idea! We should probably do that with more of our default classes 👍

**Comment by nataliq** [comment]
@Goos @JohnSundell 
Here we go: https://github.com/spotify/HubFramework/pull/230

**Pull request closed without merging**
