### PR TITLE
Avoid HUBComponentWrapper state saves before configure

### PR DESCRIPTION
**Pull request by Goos**
Fixes a bug where the HUBComponentWrapper would occasionally save its UI state before having been configured properly.

@spotify/objc-dev

### CODE REVIEW

**Comment by rastersize** [comment]
@Goos FYI:
```
[19:42:25]: ▸ ⚠️  /Users/travis/build/spotify/HubFramework/tests/HUBComponentWrapperTests.m:104:5: Null is returned from a method that is expected to return a non-null value
[19:42:25]: ▸ return nil;
[19:42:25]: ▸     ^~~~~~~~~~
```

**Comment by JohnSundell** [comment]
@rastersize Shouldn't our super strict build settings catch that? 😱

**Comment by Goos** [comment]
Yeah I was a bit surprised I was allowed to do that 😮  can I leave it or should we return something there in case future builds pick up the warning?

**Comment by JohnSundell** [comment]
@Goos I'd add an `XCTFail` call in that method and then return `(HUBComponentWrapper *)nil`.

**Pull request merged**
