### PR TITLE
View controller: Don’t reconfigure header/overlay components serving the same model

### PR DESCRIPTION
**Pull request by JohnSundell**
Similar to how we deal with body components (with diffing), there’s no need to reconfigure a header or overlay component if it’s going to serve the exact same model as its currently serving.

### CODE REVIEW

**Comment by JohnSundell** [comment]
@spotify/objc-dev

**Comment by cerihughes** [comment]
@JohnSundell Is this just a short-term solution / quick fix? Would a better / longer term solution be to consider headers and overlays in the existing diffing code and return diffed results for each component type?

**Comment by JohnSundell** [comment]
@cerihughes Yeah it would probably be a good idea to move all code doing any diffing into `HUBViewModelDiff`. For now there's already quite an amout of "diffing code" (although very simple) in the view controller for overlay components - would love to refactor that - but let's do it in a separate PR 😄

**Comment by JohnSundell** [comment]
@cerihughes With this we also have the tests in place to make sure that our future refactor won't break anything 🚀

**Comment by cerihughes** [comment]
@JohnSundell - Yeah, that makes sense. Let's create an issue to move all diffing code into the same place.

**Comment by JohnSundell** [comment]
@cerihughes Done! https://github.com/spotify/HubFramework/issues/144

**Pull request merged**
