### PR TITLE
View controller: Add API to retrieve a single visible component view

### PR DESCRIPTION
**Pull request by JohnSundell**
This new API is an alternative to returning **all** visible component views, and provides a much faster (pretty much `O(1)` complexity - if you disregard the length of the index path) way of looking up just a **single** component view.

### CODE REVIEW

**Comment by JohnSundell** [comment]
@spotify/objc-dev

**Comment by cerihughes** [comment]
Sorry for the delay in reviewing, but why doesn't `visibleViewForComponentOfType:indexPath:` just do

```
- (nullable UIView *)visibleViewForComponentOfType:(HUBComponentType)componentType indexPath:(NSIndexPath *)indexPath
{
    return [self visibleComponentViewsForComponentType:componentType][indexPath];
}
```

**Comment by cerihughes** [comment]
Oh, for complexity reasons?

**Comment by cerihughes** [comment]
Sorry. I should have read the PR description!

**Comment by cerihughes** [comment]
👍

**Comment by JohnSundell** [comment]
@cerihughes Yeah exactly, basically in the Spotify app, we're calling this as part of handling a gesture recognizer, so need to have close to `O(1)` complexity to not hog the main tread 😄

**Pull request merged**
