### PR TITLE
Expose the default scroll handler as a override point

### PR DESCRIPTION
**Pull request by nataliq**
Moves the `HUBViewControllerDefaultScrollHandler` to the include folder so that it could be subclassed by features that want to provide different implementation just for few methods. Apart from that only the description of the class is slightly modified.

### CODE REVIEW

**Comment by nataliq** [comment]
@Goos right, added. It was a small change so I rebased hope you don't mind :D

**Comment by Goos** [comment]
No worries, still approved :smile: 👍

**Comment by rastersize** [comment]
👍

**Comment by rastersize** [comment]
Closing this PR in favor of #250 which takes @nataliq’s commits and then also applies a final commit to fix the build error.

**Pull request closed without merging**
