### PR TITLE
Simplify the generation of the index path.

### PR DESCRIPTION
**Pull request by cerihughes**
Instead of storing the indices in reverse order, then iterating in reverse, store them in the order they'll be accessed in.

Also gets around a static analyser warning, which claims we could return `nil` from the method (which wasn't strictly true).

### CODE REVIEW

**Comment by cerihughes** [comment]
@krris : This gets rid of the static analyser warning.

**Comment by Goos** [comment]
Could we also avoid boxing them by using an `NSIndexSet`? We would still have to use reverse enumeration for them then though as they are implicitly ordered

**Comment by JohnSundell** [comment]
@cerihughes The conflict is because of me (sorry!) 😛 I added a workaround for the static analyzer warning here: https://github.com/spotify/HubFramework/pull/87/commits/0550094089dc8e7dca5a936221bdae28008a45e8. But I like this approach better! So feel free to pick your implementation when rebasing 😄

**Comment by JohnSundell** [comment]
Wooops, accidental close 😢

**Pull request merged**
